# Generated by Django 6.0.1 on 2026-01-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_pub_data_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quetion',
            new_name='question',
        ),
    ]
